# Generated by Django 4.2.4 on 2024-02-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_meal_number_of_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
